### ISSUE TITLE
Feature request: more compact display

### ISSUE THREAD

**Issue by timholy** [essenciary/PkgSearch.jl#4]
It would be lovely if under typical usage, a whole page of 10 results would fit on my screen without me having to scroll the window---it would make searches considerably more efficient. Maybe something like

```
Images (registered): https://github.com/timholy/Images.jl
An image library for julia
<search result sample>

OpenCV.jl (unregistered): git://github.com/maxruby/OpenCV.jl.git
The OpenCV (C++) interface for Julia
<search result sample>
...
```

At 4 lines per item, it should fit in a single window if you suppress the return output with `;`.

**Comment by essenciary** [comment]
Yes, sure, good idea. I can replace the "Official package" row with an √ similar to http://genieframework.com/packages - and add the URL on the same line with the title.

**Comment by essenciary** [comment]
@timholy Thanks for the suggestion, added and pushed to git. 

However, suppressing the output does not seem to work - I've tried adding `;` to the various functions called by `lookup()`, still can't get rid of the output.

**Comment by timholy** [comment]
Thanks!

As far as suppressing the output goes, that's up to the user: `PkgSearch.lookup("foo");` with a semicolon at the end. There's nothing you can do in the package to control whether output is printed, short of not returning anything.
